### ISSUE TITLE
Drop .ipynb_checkpoints from the repo

### ISSUE THREAD

**Issue by mjuric** [maria8ch/iCompare#1]
Thanks for creating the repo!

One thing I noticed -- you may want to remove `.ipynb_checkpoints` from the repository; these are the temporary files and backup copies that Jupyter creates and that don't need to be saved. Do something like `git rm -r .ipynb_checkpoints` (& commit).

**Comment by mjuric** [comment]
Also may be good to create a `.gitignore` file -- see:
* https://medium.com/@cruble/a-quick-guide-for-making-a-git-ignore-gitignore-e645d70676b2
* https://www.toptal.com/developers/gitignore/api/jupyternotebooks

to learn more.

**Comment by maria8ch** [comment]
I dropped the files and I made a .gitignore. Should I go ahead and add the Fortran template to it along with Python, since that's something that may come up?

**Comment by mjuric** [comment]
Python + Jupyter should be sufficient for now & you can add more if/when becomes needed. I don't think you'll need to write any fortran code (🤞).

**Comment by maria8ch** [comment]
Never say never, ey. I'll add the jupyter thing into it, and close the issue once I do.

**Comment by maria8ch** [comment]
Jupyter isn't in the templates, but the python thing seems to suppress everything. Closing this issue.

**Comment by mjuric** [comment]
[This](https://www.toptal.com/developers/gitignore/api/jupyternotebooks) should cover Jupyter temporary files (mostly `ipynb_checkpoints`).
